# Replication of the GPT-2/WikiText experiment from MAGIC (arXiv 2504.16430,
# App. A).

# Hyperparameters are inferred from the MAGIC paper, the metagradients
# paper it cites, and the datacomp competition that the metagradients paper cites.
# The original batch size was lost.

# Run with `bergson examples/magic/gpt2_wikitext.yaml`

steps:
  - magic:
      run_path: runs/gpt2_wikitext
      model: gpt2
      overwrite: false
      cleanup_ckpts: false

      # Inferred from MAGIC
      weight_decay: 1.0e-05
      # Inferred from DataComp-small
      adam_eps: 1.0e-06
      # Inferred from metagradient descent paper
      loss_reduction: sum_of_means

      data:
        dataset: EleutherAI/bergson-wikitext-512-chunks
        split: "train"
        chunk_length: 0
        truncation: true

      query:
        dataset: EleutherAI/bergson-wikitext-512-chunks
        split: "test[0:1]"
        chunk_length: 0

      distributed:
        nproc_per_node: 4
        nnode: 4

      # Original batch size lost
      batch_size: 256
      num_epochs: 4
      lr_schedule:
        lr_scheduler_type: polynomial
        lr: 0.0008
        lr_start: 1e-6
        lr_end: 0.00008
        warmup_steps: 0.25

      subset_strategy: random
      wandb_project: magic
      num_subsets: 400
      subset_fraction: 0.01
      save_optimizer_state: True
      save_retrained_models: True
