# Compute TrackStar attribution scores for a model generated
# using q3_magic.yaml using test[3:4] as the query, then run leave-k-out
# validation on those scores.

# Run with `bergson examples/magic/compare/q3_trackstar.yaml`

run_path: runs/compare/q3_trackstar
steps:
  - trackstar:
      index_cfg:
        projection_dim: 16
        run_path: runs/compare/q3_trackstar
        model: runs/compare/q3_random/hf_model
        overwrite: true
        # GPT-2's max context length is 1024
        token_batch_size: 1024
        # GPT-2 uses an nn.Linear for its LM head.
        filter_modules: "lm_head"
        distributed:
          nproc_per_node: 4
          nnode: 4
        data:
          dataset: Salesforce/wikitext
          subset: wikitext-2-raw-v1
          split: "train"
          chunk_length: 0
          truncation: true

      trackstar_cfg:
        stats_sample_size: 10000
        query:
          dataset: Salesforce/wikitext
          subset: wikitext-2-raw-v1
          split: "test[3:4]"
          chunk_length: 0
          truncation: true
        preprocess_cfg:
          unit_normalize: true
          aggregation: mean
        score_cfg:
          batch_size: 1024

  - validate:
      run_path: runs/compare/q3_validate_trackstar_random
      model: gpt2
      overwrite: true

      scores: runs/compare/q3_trackstar/scores

      data:
        dataset: Salesforce/wikitext
        subset: wikitext-2-raw-v1
        split: "train"
        chunk_length: 512

      query:
        dataset: Salesforce/wikitext
        subset: wikitext-2-raw-v1
        split: "test[3:4]"
        chunk_length: 0

      distributed:
        nproc_per_node: 4
        nnode: 4

      batch_size: 256
      num_epochs: 2
      lr_schedule:
        lr_scheduler_type: polynomial
        lr: 0.0008
        lr_start: 1e-6
        lr_end: 0.00008
        warmup_steps: 0.25

      subset_strategy: random
      wandb_project: magic

  - validate:
      run_path: runs/compare/q3_validate_trackstar_sorted
      model: gpt2
      overwrite: true

      scores: runs/compare/q3_trackstar/scores

      data:
        dataset: Salesforce/wikitext
        subset: wikitext-2-raw-v1
        split: "train"
        chunk_length: 512

      query:
        dataset: Salesforce/wikitext
        subset: wikitext-2-raw-v1
        split: "test[3:4]"
        chunk_length: 0

      distributed:
        nproc_per_node: 4
        nnode: 4

      batch_size: 256
      num_epochs: 2
      lr_schedule:
        lr_scheduler_type: polynomial
        lr: 0.0008
        lr_start: 1e-6
        lr_end: 0.00008
        warmup_steps: 0.25

      subset_strategy: sorted
      wandb_project: magic

  - validate:
      run_path: runs/compare/q3_validate_trackstar_random_exclude_0
      model: gpt2
      overwrite: true

      scores: runs/compare/q3_trackstar/scores

      data:
        dataset: Salesforce/wikitext
        subset: wikitext-2-raw-v1
        split: "train"
        chunk_length: 512

      query:
        dataset: Salesforce/wikitext
        subset: wikitext-2-raw-v1
        split: "test[3:4]"
        chunk_length: 0

      distributed:
        nproc_per_node: 4
        nnode: 4

      batch_size: 256
      num_epochs: 2
      lr_schedule:
        lr_scheduler_type: polynomial
        lr: 0.0008
        lr_start: 1e-6
        lr_end: 0.00008
        warmup_steps: 0.25

      subset_strategy: random
      exclude_zero_scores: true
      wandb_project: magic

  - validate:
      run_path: runs/compare/q3_validate_trackstar_sorted_exclude_0
      model: gpt2
      overwrite: true

      scores: runs/compare/q3_trackstar/scores

      data:
        dataset: Salesforce/wikitext
        subset: wikitext-2-raw-v1
        split: "train"
        chunk_length: 512

      query:
        dataset: Salesforce/wikitext
        subset: wikitext-2-raw-v1
        split: "test[3:4]"
        chunk_length: 0

      distributed:
        nproc_per_node: 4
        nnode: 4

      batch_size: 256
      num_epochs: 2
      lr_schedule:
        lr_scheduler_type: polynomial
        lr: 0.0008
        lr_start: 1e-6
        lr_end: 0.00008
        warmup_steps: 0.25

      subset_strategy: sorted
      exclude_zero_scores: true
      wandb_project: magic
